import Head from "next/head";

import styles from "../styles/Home.module.css";

import HeaderContainer from "../components/header-container";
import Topics from "../components/topics";
import HighlightPosts from "../components/highlight-posts";
import LatestNews from "../components/latest-news";
import MustReads from "../components/must-reads";
import Subscription from "../components/subscription";
import Articles from "../components/articles";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Leafwell - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeaderContainer />
        <Topics />
        <HighlightPosts />
        <LatestNews />
        <MustReads />
        <Subscription />
        <Articles />
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
